### ISSUE TITLE
Can't able to stream 

### ISSUE THREAD

**Issue by MoonWalker440** [fsmdeveloper/hdo-box#1]
Hey there, I always get [this error](https://graph.org/file/d5976dabcf0091eb954b3.jpg). Can you able to fix it ? Also the home feed is pretty old. Can't find any new movies there. Needed a fix update

**Comment by fsmdeveloper** [comment]
Sorry to hear that! I'm currently working on the app.

Please check the movies page on the app to see trending movies. You can also find new movies using the search page.

I'm working on the download features and will update the home feed soon.

If you see the "stream server is busy" error, that means this movie is not available right now. Please check another movie. Most of the movies and TV series are working

**Comment by MoonWalker440** [comment]
Alright !! Gotcha
