### ISSUE TITLE
not able to use Auto-Rotate Screen inside player

### ISSUE THREAD

**Issue by byVNVS** [fsmdeveloper/hdo-box#5]
The auto-rotate screen feature does not seem to working inside the player, perhaps the android:screenOrientation property is set to one orientation only

For the PlayerActivity this needs to be changed to something like android:screenOrientation="sensor"

**Comment by byVNVS** [comment]
Perhaps, It was a mistake on my end. Checked this after updating the app and it seems to be working fine. Sorry for the confusion

**Comment by fsmdeveloper** [comment]
I'll fix it today, and push an update. Thank you.

**Comment by fsmdeveloper** [comment]
> Perhaps, It was a mistake on my end. Checked this after updating the app and it seems to be working fine. Sorry for the confusion

Thanks bro!
